# Generated by Django 4.2.4 on 2023-08-05 13:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("assignments", "0003_alter_order_discipline_alter_order_type_of_paper"),
        ("accounts", "0001_initial"),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="OrderItem",
            new_name="Transaction",
        ),
    ]
