# Generated by Django 4.2.4 on 2023-08-06 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("payments", "0003_remove_transaction_status_transaction_completed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="email_address",
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_payment",
                to="accounts.profile",
            ),
        ),
    ]
