# Generated by Django 4.2.4 on 2023-08-05 12:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("assignments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "topic",
                    models.CharField(help_text="Tell us your topic", max_length=100),
                ),
                ("type_of_paper", models.CharField(choices=[], max_length=100)),
                ("discipline", models.CharField(choices=[], max_length=100)),
                ("pages", models.PositiveBigIntegerField(default=1)),
                ("words", models.PositiveBigIntegerField(default=275)),
                (
                    "academic_level",
                    models.CharField(
                        choices=[
                            ("DA", "Dont Apply"),
                            ("HS", "High School"),
                            ("CG", "College"),
                            ("UG", "Undergraduate"),
                            ("MS/PDH", "Masters/Phd"),
                        ],
                        default="UG",
                        max_length=10,
                    ),
                ),
                ("deadline", models.DateTimeField(default=django.utils.timezone.now)),
                ("paper_instruction", models.TextField(blank=True, null=True)),
                ("files", models.FileField(blank=True, null=True, upload_to="orders/")),
                (
                    "paper_format",
                    models.CharField(
                        choices=[
                            (
                                "APA",
                                (
                                    ("APA6", "APA 6"),
                                    ("APA7", "APA 7"),
                                    ("APA9", "APA 9"),
                                ),
                            ),
                            ("MLA", "MLA"),
                            ("CHICAGO", "Chicago/Turabian"),
                            ("NA", "Not Applicable"),
                            ("HARVARD", "Harvard"),
                            ("OTHER", "OTHER"),
                        ],
                        default="APA",
                        max_length=100,
                    ),
                ),
                (
                    "type_of_service",
                    models.CharField(
                        choices=[
                            ("SW", "Sample Writing"),
                            ("ER", "Editting Rewriting"),
                            ("CALC", "Calculations"),
                        ],
                        default="SW",
                        max_length=10,
                    ),
                ),
                ("reference_copies", models.BooleanField(default=False)),
                ("sms_update", models.BooleanField(default=False)),
                ("turnitin_report", models.BooleanField(default=False)),
                (
                    "writer_choice",
                    models.CharField(
                        choices=[
                            ("RW", "Regular Writer"),
                            ("FW", "First Writer"),
                            ("PW", "Professional Writer"),
                        ],
                        default="RW",
                        max_length=2,
                    ),
                ),
                (
                    "ppt",
                    models.CharField(blank=True, choices=[], max_length=100, null=True),
                ),
                ("software_tools", models.BooleanField(default=False)),
                ("software_tool_description", models.TextField(blank=True, null=True)),
                ("weekly", models.BooleanField(default=False)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("order_id", models.CharField(blank=True, max_length=12, null=True)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_client",
                        to="accounts.profile",
                    ),
                ),
            ],
            options={
                "get_latest_by": "createdAt",
            },
        ),
    ]
