# Generated by Django 4.2.4 on 2023-08-05 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assignments", "0002_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="discipline",
            field=models.CharField(
                choices=[("Jeckonia", "Jeckonia"), ("CK EDITOR72", "CK EDITOR72")],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="type_of_paper",
            field=models.CharField(
                choices=[
                    ("Jeckonia Onyango", "Jeckonia Onyango"),
                    ("ehwrh5re", "ehwrh5re"),
                    ("Daniel Milimo", "Daniel Milimo"),
                    ("ytjyse", "ytjyse"),
                ],
                max_length=100,
            ),
        ),
    ]
