# Generated by Django 4.2.4 on 2023-08-05 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("assignments", "0003_alter_order_discipline_alter_order_type_of_paper"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_daily",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="WeeklyAssigment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("school_id", models.CharField(max_length=100)),
                ("school_name", models.CharField(max_length=100)),
                ("moodle_account_link", models.URLField(max_length=255)),
                ("number_of_subjects", models.PositiveIntegerField(default=1)),
                (
                    "login_details",
                    models.CharField(
                        help_text="username and password for the moodle account",
                        max_length=300,
                    ),
                ),
                (
                    "subjects_details",
                    models.TextField(
                        help_text="Subject details eg, subject title and code"
                    ),
                ),
                ("duration", models.DateTimeField(auto_now_add=True)),
                ("is_weekly", models.BooleanField(default=True)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.profile",
                    ),
                ),
            ],
        ),
    ]
