# Generated by Django 4.2.4 on 2023-08-06 08:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("assignments", "0005_order_price_alter_order_discipline_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="deadline",
        ),
        migrations.AddField(
            model_name="order",
            name="deadline_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="order",
            name="deadline_time",
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
