# Generated by Django 4.2.4 on 2023-08-06 10:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("assignments", "0006_remove_order_deadline_order_deadline_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="deadline_time",
            field=models.TimeField(default=django.utils.timezone.now, help_text="H:M"),
        ),
        migrations.AlterField(
            model_name="order",
            name="price",
            field=models.DecimalField(decimal_places=2, default=1.34, max_digits=12),
        ),
    ]
