# Generated by Django 4.2.4 on 2023-08-06 10:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assignments", "0007_alter_order_deadline_time_alter_order_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="price",
            field=models.FloatField(),
        ),
    ]
