# Generated by Django 4.2.4 on 2023-08-06 11:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assignments", "0009_alter_order_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="slug",
            field=models.SlugField(default="topic", max_length=100),
            preserve_default=False,
        ),
    ]
