# Generated by Django 4.2.4 on 2023-08-07 04:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assignments", "0010_order_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="ppt",
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
