# Generated by Django 4.2.4 on 2023-08-09 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assignments", "0014_weeklyassigment_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weeklyassigment",
            name="duration",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
